name: hotspot
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - ipympl
  - ipykernel
  - ipython
  - jupyter_console
  - jupyterlab
  - numpy
  - pytest
  - matplotlib
  - h5py
  - pySerial
  - pip:
    - pycallgraph2
    - portray
    - prompt-toolkit<=2.0.0
